package com.example.musicapp.navigation

object ObjRoutes {
    const val SPLASH = "SplashRoute"
    const val LOGINREG = "LoginRegRoute/{id}"
    fun loginReg(id: String) = "LoginRegRoute/$id"
    const val LOGIN = "LoginRoute/{id}"
    fun login(id: String) = "LoginRoute/$id"
    const val REGISTER="RegisterRoute/{id}"
    fun register(id: String) = "RegisterRoute/$id"
    const val MAINSCREEN = "MainScreenRoute/{id}"
    fun mainScreen(id: String) = "MainScreenRoute/$id"
    const val AE="BandAeRoute/{id}"
    fun bandAe(id: String) = "BandAeRoute/$id"
    const val BOC="BandBocRoute/{id}"
    const val APHX="BandAphxRoute/{id}"
    const val KYUSS="BandKyussRoute/{id}"
    const val TOOL="BandToolRoute/{id}"
    const val INFOUSER="UserInfoRoute/{id}"
    const val SETTINGS="SettingsRoute"
    //const val DIALOG=""
    //fun detalle(id: String) = "detalle/$id"
    const val HOME = "home"
    const val SEARCH = "search"
    const val PROFILE = "profile"
}